
export enum types {
     SET_PRODUCT = "SET_PRODUCT",
     SET_PRODUCTS = "SET_PRODUCTS",
     FETCH_PRODUCTS_ASYNC = "FETCH_PRODUCTS_ASYNC",
     FETCH_PRODUCT_ASYNC = "FETCH_PRODUCT_ASYNC"
}
    

